version: "3.9"

services:
    # Backend HTTP API Service (Development)
    backend-http:
        build:
            context: ./backend
            dockerfile: Dockerfile.http
        ports:
            - "4200:4200"
        environment:
            - NODE_ENV=development
            - PORT=4200
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - app-network
        restart: unless-stopped
        command: npm run dev-http-db

    # Backend GraphQL API Service (Development)
    backend-graphql:
        build:
            context: ./backend
            dockerfile: Dockerfile.graphql
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=development
            - PORT=4000
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - app-network
        restart: unless-stopped
        command: npm run dev-graphql

    # Frontend Service (Development)
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        depends_on:
            - backend-http
            - backend-graphql
        networks:
            - app-network
        restart: unless-stopped
        environment:
            - VITE_API_URL=http://localhost:4200
            - VITE_GRAPHQL_URL=http://localhost:4000
        volumes:
            - ./frontend:/app
            - /app/node_modules

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
