version: "3.9"

services:
    # Backend HTTP API Service
    backend-http:
        build:
            context: ./backend
            dockerfile: Dockerfile.http
        ports:
            - "4200:4200"
        environment:
            - NODE_ENV=production
            - PORT=4200
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - app-network
        restart: unless-stopped

    # Backend GraphQL API Service
    backend-graphql:
        build:
            context: ./backend
            dockerfile: Dockerfile.graphql
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=production
            - PORT=4000
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - app-network
        restart: unless-stopped

    # Frontend Service
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - backend-http
            - backend-graphql
        networks:
            - app-network
        restart: unless-stopped
        environment:
            - REACT_APP_API_URL=http://localhost:4200
            - REACT_APP_GRAPHQL_URL=http://localhost:4000

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
